### ISSUE TITLE
Support the IBC skills Matrix within the Website

### ISSUE THREAD

**Issue by zmanian** [cosmos/stargate#27]
The IBC Skills Matrix and Flow of Funds model we started to develop here is going to be very important to IBC go to market.

https://github.com/cosmosdevs/stargate/blob/master/ibc_readiness_matrix.md

Any thoughts on how to get this into the website?

**Comment by nassdonald** [comment]
Sure! We should probably make a separate page for this. I'll have a think about how to visualize it, so I'll be in touch with questions no doubt. 🙂
