### ISSUE TITLE
"Vote" button on Stargate page should lead to proposal #37

### ISSUE THREAD

**Issue by Tosch110** [cosmos/stargate#84]
Vote button on Stargate page goes to proposal cosmos/cosmos.network#36 on the hub.

This should be https://www.mintscan.io/cosmos/proposals/37 now

**Comment by Tosch110** [comment]
Ahh... wrong repo. Sorry 🙏

**Comment by Tosch110** [comment]
Thanks for the transfer!

**Comment by lovincyrus** [comment]
![image](https://user-images.githubusercontent.com/1021101/106339888-d4134000-624c-11eb-8e79-c7deeab27c32.png)

Should I update the end date to Feb 11? @Tosch110

**Comment by Tosch110** [comment]
Voting will end 2021-02-12 06:35:54 and the Update will happen 06:00 UTC on Feb 18th

Maybe both "Vote 'Yes' on the proposal until Feb 12th to bring the Stargate upgrades to the Cosmos Hub on Feb 18th"
