### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by faza** [cosmos/stargate#94]
### Environment
go version go1.16.2 linux/amd64
starport version v0.15.0 linux/amd64 -build date: 2021-03-16T06:22:49Z

### Steps to reproduce
```
$ starport app github.com/testapp/testapp
$ cd testapp
$ starport type whois value
$ starport serve
```

### Error details
```
$ starport serve
Cosmos SDK's version is: Stargate v0.40.0 (or above)

🛠️  Building proto...
📦 Installing dependencies...
🛠️  Building the app...
cannot build app:

	# github.com/testapp/testapp/x/testapp/keeper
../../x/testapp/keeper/whois.go:55:8: no new variables on left side of :=
../../x/testapp/keeper/whois.go:55:8: cannot use k.cdc.MustMarshalBinaryBare(&whois) (type []byte) as type string in assignment
../../x/testapp/keeper/whois.go:56:27: cannot use value (type string) as type []byte in argument to store.Set

Waiting for a fix before retrying...

```

### Relevant code snippet
![Screenshot from 2021-03-22 21-51-15](https://user-images.githubusercontent.com/3815875/112023196-08262580-8b59-11eb-8526-34a470379c6c.png)

**Comment by lovincyrus** [comment]
Hi @faza, thanks for reporting this issue. This repo is a website for `stargate`. Would you mind reopening the same issue in this `starport` repo https://github.com/tendermint/starport instead?

**Comment by faza** [comment]
Sorry, my bad. I'll do that.

**Comment by lazizcodes** [comment]
Hi @faza, could you share a link to the issue you opened there? Have you found a solution? I'm having a kind of similar issue.
